<?php

return [
    'grapesjs' => [
        'label' => 'Contenu libre',
        'icon' => 'fas fa-pen-fancy',
        'category' => 'content',
        'editor' => 'grapesjs',
        'description' => 'Bloc éditable avec l\'éditeur visuel GrapesJS',
        'default_config' => [],
    ],
    'hero' => [
        'label' => 'Bannière hero',
        'icon' => 'fas fa-image',
        'category' => 'content',
        'editor' => 'form',
        'description' => 'Grande bannière avec titre, sous-titre et image',
        'default_config' => [
            'title' => '',
            'subtitle' => '',
            'image_url' => '',
            'cta_label' => '',
            'cta_url' => '',
        ],
    ],
    'cantine-menus' => [
        'label' => 'Menus cantine',
        'icon' => 'fas fa-utensils',
        'category' => 'module',
        'editor' => 'form',
        'description' => 'Menus de la cantine du mois en cours',
        'requires_module' => 'cantine',
        'default_config' => [
            'month_offset' => 0,
            'limit' => 10,
            'show_image' => false,
        ],
    ],
    'news-list' => [
        'label' => 'Actualités',
        'icon' => 'fas fa-newspaper',
        'category' => 'module',
        'editor' => 'form',
        'description' => 'Dernières actualités publiées',
        'requires_module' => 'public_site_news',
        'default_config' => [
            'limit' => 4,
            'layout' => 'grid',
            'show_image' => true,
        ],
    ],
    'events-upcoming' => [
        'label' => 'Événements',
        'icon' => 'fas fa-calendar-days',
        'category' => 'module',
        'editor' => 'form',
        'description' => 'Prochains événements de la commune',
        'requires_module' => 'public_site_events',
        'default_config' => [
            'limit' => 4,
            'show_image' => true,
        ],
    ],
    'procedures' => [
        'label' => 'Démarches',
        'icon' => 'fas fa-list-check',
        'category' => 'module',
        'editor' => 'form',
        'description' => 'Liens vers les démarches administratives (service-public.fr, etc.)',
        'default_config' => [
            'items' => [
                ['label' => 'Carte d\'identité', 'url' => 'https://www.service-public.fr/particuliers/vosdroits/N358', 'icon' => 'fas fa-id-card', 'category' => 'État civil'],
                ['label' => 'Passeport', 'url' => 'https://www.service-public.fr/particuliers/vosdroits/N360', 'icon' => 'fas fa-passport', 'category' => 'État civil'],
                ['label' => 'Recensement citoyen', 'url' => 'https://www.service-public.fr/particuliers/vosdroits/R2054', 'icon' => 'fas fa-person-military-pointing', 'category' => 'État civil'],
                ['label' => 'Acte de naissance', 'url' => 'https://www.service-public.fr/particuliers/vosdroits/N359', 'icon' => 'fas fa-file-lines', 'category' => 'État civil'],
                ['label' => 'Certificat de résidence', 'url' => '', 'icon' => 'fas fa-house', 'category' => 'État civil'],
                ['label' => 'Inscription listes électorales', 'url' => 'https://www.service-public.fr/particuliers/vosdroits/R2057', 'icon' => 'fas fa-check-to-slot', 'category' => 'Élections'],
            ],
        ],
    ],
    'documents' => [
        'label' => 'Documents',
        'icon' => 'fas fa-folder-open',
        'category' => 'module',
        'editor' => 'form',
        'description' => 'Liste de documents téléchargeables (bulletins, arrêtés, comptes-rendus)',
        'default_config' => [
            'items' => [
                ['label' => 'Bulletin municipal', 'url' => '', 'category' => 'Bulletins', 'date' => ''],
                ['label' => 'Compte-rendu du conseil municipal', 'url' => '', 'category' => 'Conseil municipal', 'date' => ''],
                ['label' => 'Arrêtés municipaux', 'url' => '', 'category' => 'Arrêtés', 'date' => ''],
            ],
        ],
    ],
    'council' => [
        'label' => 'Conseil municipal',
        'icon' => 'fas fa-people-group',
        'category' => 'module',
        'editor' => 'form',
        'description' => 'Membres du conseil municipal avec leur fonction',
        'default_config' => [
            'members' => [
                ['name' => '', 'role' => 'Maire', 'photo_url' => '', 'delegation' => ''],
            ],
            'deliberations_url' => '',
        ],
    ],
    'weather' => [
        'label' => 'Météo',
        'icon' => 'fas fa-cloud-sun',
        'category' => 'widget',
        'editor' => 'form',
        'description' => 'Météo actuelle de la commune (Open-Meteo)',
        'default_config' => [
            'show_forecast' => true,
        ],
    ],
    'social' => [
        'label' => 'Réseaux sociaux',
        'icon' => 'fas fa-share-nodes',
        'category' => 'widget',
        'editor' => 'form',
        'description' => 'Boutons vers vos réseaux sociaux',
        'default_config' => [
            'facebook_url' => '',
            'instagram_url' => '',
            'twitter_url' => '',
            'youtube_url' => '',
            'style' => 'rounded',
        ],
    ],
    'hours' => [
        'label' => 'Horaires d\'ouverture',
        'icon' => 'fas fa-clock',
        'category' => 'widget',
        'editor' => 'form',
        'description' => 'Horaires d\'ouverture de la mairie',
        'default_config' => [
            'monday' => ['open' => '08:30', 'close' => '12:00', 'open2' => '13:30', 'close2' => '17:00'],
            'tuesday' => ['open' => '08:30', 'close' => '12:00', 'open2' => '13:30', 'close2' => '17:00'],
            'wednesday' => ['open' => '08:30', 'close' => '12:00', 'open2' => '13:30', 'close2' => '17:00'],
            'thursday' => ['open' => '08:30', 'close' => '12:00', 'open2' => '13:30', 'close2' => '17:00'],
            'friday' => ['open' => '08:30', 'close' => '12:00', 'open2' => '13:30', 'close2' => '17:00'],
            'saturday' => null,
            'sunday' => null,
        ],
    ],
    'contact' => [
        'label' => 'Contact',
        'icon' => 'fas fa-envelope',
        'category' => 'widget',
        'editor' => 'form',
        'description' => 'Coordonnées de la mairie avec formulaire de contact optionnel',
        'default_config' => [
            'address_override' => '',
            'phone_override' => '',
            'email_override' => '',
            'show_form' => true,
            'map_url' => '',
        ],
    ],
];
